fix: don't test for runtimeType equality for object comparison take 2
felangel/equatable pull request #192
Opened 2024-11-22 21:45 UTC by devmil

## Status
**READY**

## Breaking Changes
NO

## Description
Continuation of #188 
As discussed in the referenced PR here an extended PR that adds a couple of tests to make sure that Equatable comparison still works as intended (e.g. different classes with same property values should be different) as well as adding a very far-fetched test-case that simulates non-Equatable classes with custom equality logic.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
master | [link](https://github.com/felangel/equatable/pull/188)

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Examples

## Steps to Test or Reproduce
Have an Equatable class with a field that's type is using a custom equality logic

```
class CustomEqualityVariant1;
class CustomEqualityVariant2;

final val1 = CustomEqualityVariant1();
final val2 = CustomEqualityVariant2();
val1 == val2

final equatableInstance1 = EquatableClass(val1);
final equatableInstance2 = EquatableClass(val2);

instance1 != instance2 // this was not the case pre 2.0.6
```

## Impact to Remaining Code Base
This PR will affect:

* None, restores pre 2.0.6 behavior

2024-11-27 19:47 UTC, felangel requested changes
I took a closer look at v2.0.5 and this was not a breaking change from what I can see ([runtimeType was still considered in the equality check](https://github.com/felangel/equatable/blob/2117551ff3054f8edb1a58f63ffe1832a8d25623/lib/src/equatable_utils.dart#L25)). The new test you added fails in v2.0.5.

2024-11-27 19:57 UTC, devmil commented
> I took a closer look at v2.0.5 and this was not a breaking change from what I can see ([runtimeType was still considered in the equality check](https://github.com/felangel/equatable/blob/2117551ff3054f8edb1a58f63ffe1832a8d25623/lib/src/equatable_utils.dart#L25)). The new test you added fails in v2.0.5 so I don't think we should change this behavior now.

@felangel 
True. Then I will take a deeper look on why equatable 2.0.6 (and 2.0.7 as well) breaks our code base and create a new PR.

But don't you think that the behavior expressed in the new unit tests is wrong? Regardless of being introduced in 2.0.6 or not?

2024-11-28 11:13 UTC, devmil commented
@felangel 
I digged deeper and found out why 2.0.6/2.0.7 break our code.
The piece of code is not using the custom equality objects directly but they are in a list.
2.0.5 branched out to the DeepCollectionEquality which internally doesn't do runtimeType checks (because it doesn't need to)
2.0.6 replaced that approach with a custom list equality logic that falls back to the equals logic that uses the runtimeType as a condition.
I added a test that works in this branch but fails on 2.0.6/2.0.7 to showcase the scenario

2025-01-02 17:06 UTC, felangel commented
> @felangel I digged deeper and found out why 2.0.6/2.0.7 breaks our code. The piece of code is not using the custom equality objects directly but they are in a list. 2.0.5 branched out to the DeepCollectionEquality which internally doesn't do runtimeType checks (because it doesn't need to)
> 
> https://github.com/felangel/equatable/blob/2117551ff3054f8edb1a58f63ffe1832a8d25623/lib/src/equatable_utils.dart#L24
> 
> 
> 2.0.6 replaced that approach with a custom list equality logic that uses the equatable equals logic (that has the runtimeType condition) for each item.
> https://github.com/felangel/equatable/blob/49c860437d0d3cfb7c386bfe9b09c8f352b6f25e/lib/src/equatable_utils.dart#L19
> 
> 
> I added a test that works in this branch as well as on 2.0.5 but fails on 2.0.6/2.0.7 to showcase the scenario

Sorry for the delay (I was off for a lot of the holidays). Will try to get this merged later today or tomorrow 👍

2025-01-02 17:59 UTC, devmil commented
> Sorry for the delay (I was off for a lot of the holidays). Will try to get this merged later today or tomorrow 👍
No problem. We have a workaround by now.
I think it makes sense to do a major jump if you decide to take the changes in this PR as the behavior is different.

2025-01-17 19:12 UTC, felangel commented
> > Sorry for the delay (I was off for a lot of the holidays). Will try to get this merged later today or tomorrow 👍
> 
> No problem. We have a workaround by now. I think it makes sense to do a major jump if you decide to take the changes in this PR as the behavior is different.

Yeah need to double check if this issue exists in the v3.0.0-dev release (macros rewrite). If not, we can fix it in the v3.0.0 pre-release 👍 

Glad you have a workaround 😄

2026-09-15 19:20 UTC, closed without merging

2026-09-15 19:20 UTC, felangel commented
closing in favor of https://github.com/felangel/equatable/pull/219

2026-09-15 19:53 UTC, felangel commented
Closing in favor of #219